name: Deploy Backend

on:
  push:
    branches:
      - 12.x

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Replace Tokens in .env.production
        uses: cschleiden/replace-tokens@v1
        with:
          files: ".env"
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_CONNECTION: ${{ secrets.DB_CONNECTION}}

      - name: Deploy to Backend Machine
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            APP_DIR="/home/ubuntu/laravel"

            if [ ! -d "$APP_DIR" ]; then
              echo "Cloning Laravel app..."
              git clone ${{ secrets.REPO_URL }} $APP_DIR
              cd $APP_DIR
            else
              cd $APP_DIR
              echo "Stashing local changes and pulling updates..."
              git stash push -m "Auto-stash before pull"  # Save changes
              git pull origin 12.x  # Pull safely
              git stash pop  # Restore changes
            fi

            chmod +x deploy.sh
            ./deploy.sh  # Runs your script as is
